# -*- coding: utf-8 -*-
"""Yolo_V11_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eny4lmT5s1BlDi65V6KOA6gANnMlxGke
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/drive')

# Download COCO val
import torch
torch.hub.download_url_to_file('https://ultralytics.com/assets/coco2017val.zip', 'tmp.zip')  # download (780M - 5000 images)
!unzip -q tmp.zip -d datasets && rm tmp.zip  # unzip

# Validate YOLO11n on COCO8 val
!yolo val model=yolo11n.pt data='/content/drive/MyDrive/yolo dataset/data.yaml'

# Train YOLO11n on COCO8 for 3 epochs
!yolo train model=yolo11n.pt data='/content/drive/MyDrive/yolo dataset/data.yaml' epochs=50 imgsz=640

# Run inference on an image with YOLO11n
!yolo predict model='/content/runs/detect/train3/weights/best.pt' source= '/content/drive/MyDrive/yolo dataset/train/images/Acanthopagrus_Palmaris_101_jpg.rf.037c09ef463972e8ad4c21ba9bbfb419.jpg'